// WS v3 git 式快照同步的 protobuf 传输编码（P8，git-sync-redesign.md §5）。
//
// 与 JSON 帧的关系：同一动作集、同一字段语义，仅传输编码不同。协商：
//   - 连接 URL 携带 protocol=protobuf（+ pb=1&pv=2 可在 auth 应答后立即升级），或
//   - ClientInfo.protobuf = true；
// 升级后双向文本帧全部换为二进制 "pb" 前缀帧（pkg/app/websocket.go OnMessage/ToResponse）。
// "01" blob 分块二进制帧不参与 protobuf（裸 36B 会话 + 4B 序号 + 数据）。
//
// 字段号一经发布不可复用/不可改类型（前后向兼容靠新增字段）。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: internal/proto/v3/sync_v3.proto

package v3

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WSMessage 客户端→服务端二进制帧信封（"pb" 前缀之后）
type WSMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // 动作名，与 JSON 帧的 "|" 前段一致（V3Sync / V3Commit / ...）
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"` // 按 type 对应的请求消息体
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WSMessage) Reset() {
	*x = WSMessage{}
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WSMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSMessage) ProtoMessage() {}

func (x *WSMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSMessage.ProtoReflect.Descriptor instead.
func (*WSMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_v3_sync_v3_proto_rawDescGZIP(), []int{0}
}

func (x *WSMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WSMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// WSResponse 服务端→客户端应答信封（WSMessage.data 的内容）
type WSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`           // code.Code 数值
	Status        bool                   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`       // 成功与否
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`      // 提示文本（i18n）
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`            // 按动作对应的应答消息体（错误时应为空）
	Details       string                 `protobuf:"bytes,5,opt,name=details,proto3" json:"details,omitempty"`      // 错误明细（逗号拼接）
	Vault         string                 `protobuf:"bytes,6,opt,name=vault,proto3" json:"vault,omitempty"`          // 归属 vault（应答层冗余，与消息体内一致）
	Context       string                 `protobuf:"bytes,7,opt,name=context,proto3" json:"context,omitempty"`      // 旧分页通道用，v3 恒空（保形）
	PageIndex     int32                  `protobuf:"varint,8,opt,name=pageIndex,proto3" json:"pageIndex,omitempty"` // 同上恒 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WSResponse) Reset() {
	*x = WSResponse{}
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSResponse) ProtoMessage() {}

func (x *WSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSResponse.ProtoReflect.Descriptor instead.
func (*WSResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_v3_sync_v3_proto_rawDescGZIP(), []int{1}
}

func (x *WSResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *WSResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *WSResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WSResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WSResponse) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *WSResponse) GetVault() string {
	if x != nil {
		return x.Vault
	}
	return ""
}

func (x *WSResponse) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *WSResponse) GetPageIndex() int32 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

// ClientInfoMessage 握手 ClientInfo（ Negotiation 用；仅协商相关的少数字段）
type ClientInfoMessage struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version             string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Type                string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	IsDesktop           bool                   `protobuf:"varint,4,opt,name=is_desktop,json=isDesktop,proto3" json:"is_desktop,omitempty"`
	IsMobile            bool                   `protobuf:"varint,5,opt,name=is_mobile,json=isMobile,proto3" json:"is_mobile,omitempty"`
	IsPhone             bool                   `protobuf:"varint,6,opt,name=is_phone,json=isPhone,proto3" json:"is_phone,omitempty"`
	IsTablet            bool                   `protobuf:"varint,7,opt,name=is_tablet,json=isTablet,proto3" json:"is_tablet,omitempty"`
	IsMacOs             bool                   `protobuf:"varint,8,opt,name=is_mac_os,json=isMacOs,proto3" json:"is_mac_os,omitempty"`
	IsWin               bool                   `protobuf:"varint,9,opt,name=is_win,json=isWin,proto3" json:"is_win,omitempty"`
	IsLinux             bool                   `protobuf:"varint,10,opt,name=is_linux,json=isLinux,proto3" json:"is_linux,omitempty"`
	OfflineSyncStrategy string                 `protobuf:"bytes,11,opt,name=offline_sync_strategy,json=offlineSyncStrategy,proto3" json:"offline_sync_strategy,omitempty"`
	Protobuf            bool                   `protobuf:"varint,12,opt,name=protobuf,proto3" json:"protobuf,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ClientInfoMessage) Reset() {
	*x = ClientInfoMessage{}
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientInfoMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfoMessage) ProtoMessage() {}

func (x *ClientInfoMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfoMessage.ProtoReflect.Descriptor instead.
func (*ClientInfoMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_v3_sync_v3_proto_rawDescGZIP(), []int{2}
}

func (x *ClientInfoMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClientInfoMessage) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ClientInfoMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ClientInfoMessage) GetIsDesktop() bool {
	if x != nil {
		return x.IsDesktop
	}
	return false
}

func (x *ClientInfoMessage) GetIsMobile() bool {
	if x != nil {
		return x.IsMobile
	}
	return false
}

func (x *ClientInfoMessage) GetIsPhone() bool {
	if x != nil {
		return x.IsPhone
	}
	return false
}

func (x *ClientInfoMessage) GetIsTablet() bool {
	if x != nil {
		return x.IsTablet
	}
	return false
}

func (x *ClientInfoMessage) GetIsMacOs() bool {
	if x != nil {
		return x.IsMacOs
	}
	return false
}

func (x *ClientInfoMessage) GetIsWin() bool {
	if x != nil {
		return x.IsWin
	}
	return false
}

func (x *ClientInfoMessage) GetIsLinux() bool {
	if x != nil {
		return x.IsLinux
	}
	return false
}

func (x *ClientInfoMessage) GetOfflineSyncStrategy() string {
	if x != nil {
		return x.OfflineSyncStrategy
	}
	return ""
}

func (x *ClientInfoMessage) GetProtobuf() bool {
	if x != nil {
		return x.Protobuf
	}
	return false
}

// ManifestItem 清单条目
type ManifestItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`     // 服务器分配的 UUID（身份）
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"` // vault 内相对路径
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"` // blob 内容 SHA-256（JSON 键名 "hash"）
	IsNote        bool                   `protobuf:"varint,4,opt,name=is_note,json=isNote,proto3" json:"is_note,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Mtime         int64                  `protobuf:"varint,6,opt,name=mtime,proto3" json:"mtime,omitempty"` // 秒
	Ctime         int64                  `protobuf:"varint,7,opt,name=ctime,proto3" json:"ctime,omitempty"` // 秒
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestItem) Reset() {
	*x = ManifestItem{}
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestItem) ProtoMessage() {}

func (x *ManifestItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestItem.ProtoReflect.Descriptor instead.
func (*ManifestItem) Descriptor() ([]byte, []int) {
	return file_internal_proto_v3_sync_v3_proto_rawDescGZIP(), []int{3}
}

func (x *ManifestItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ManifestItem) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ManifestItem) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ManifestItem) GetIsNote() bool {
	if x != nil {
		return x.IsNote
	}
	return false
}

func (x *ManifestItem) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ManifestItem) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

func (x *ManifestItem) GetCtime() int64 {
	if x != nil {
		return x.Ctime
	}
	return 0
}

// Tombstone 客户端墓碑
type Tombstone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tombstone) Reset() {
	*x = Tombstone{}
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tombstone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tombstone) ProtoMessage() {}

func (x *Tombstone) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tombstone.ProtoReflect.Descriptor instead.
func (*Tombstone) Descriptor() ([]byte, []int) {
	return file_internal_proto_v3_sync_v3_proto_rawDescGZIP(), []int{4}
}

func (x *Tombstone) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Tombstone) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Scope 客户端声明范围（sparse 对账）
type Scope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Include       []string               `protobuf:"bytes,1,rep,name=include,proto3" json:"include,omitempty"`
	Exclude       []string               `protobuf:"bytes,2,rep,name=exclude,proto3" json:"exclude,omitempty"`
	Types         []string               `protobuf:"bytes,3,rep,name=types,proto3" json:"types,omitempty"` // note | attachment | config
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scope) Reset() {
	*x = Scope{}
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scope) ProtoMessage() {}

func (x *Scope) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scope.ProtoReflect.Descriptor instead.
func (*Scope) Descriptor() ([]byte, []int) {
	return file_internal_proto_v3_sync_v3_proto_rawDescGZIP(), []int{5}
}

func (x *Scope) GetInclude() []string {
	if x != nil {
		return x.Include
	}
	return nil
}

func (x *Scope) GetExclude() []string {
	if x != nil {
		return x.Exclude
	}
	return nil
}

func (x *Scope) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

// Op 服务端下发的操作
type Op struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            string                 `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"` // pull | move | delete（JSON 键名 "op"）
	Item          *ManifestItem          `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	From          string                 `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"` // move 的旧路径
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Op) Reset() {
	*x = Op{}
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Op) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Op) ProtoMessage() {}

func (x *Op) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Op.ProtoReflect.Descriptor instead.
func (*Op) Descriptor() ([]byte, []int) {
	return file_internal_proto_v3_sync_v3_proto_rawDescGZIP(), []int{6}
}

func (x *Op) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *Op) GetItem() *ManifestItem {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *Op) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

// Conflict 冲突项
type Conflict struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"` // modify | add
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	BaseHash      string                 `protobuf:"bytes,4,opt,name=base_hash,json=baseHash,proto3" json:"base_hash,omitempty"`
	ServerHash    string                 `protobuf:"bytes,5,opt,name=server_hash,json=serverHash,proto3" json:"server_hash,omitempty"`
	ServerMtime   int64                  `protobuf:"varint,6,opt,name=server_mtime,json=serverMtime,proto3" json:"server_mtime,omitempty"`
	LocalHash     string                 `protobuf:"bytes,7,opt,name=local_hash,json=localHash,proto3" json:"local_hash,omitempty"`
	IsNote        bool                   `protobuf:"varint,8,opt,name=is_note,json=isNote,proto3" json:"is_note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conflict) Reset() {
	*x = Conflict{}
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conflict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conflict) ProtoMessage() {}

func (x *Conflict) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conflict.ProtoReflect.Descriptor instead.
func (*Conflict) Descriptor() ([]byte, []int) {
	return file_internal_proto_v3_sync_v3_proto_rawDescGZIP(), []int{7}
}

func (x *Conflict) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Conflict) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Conflict) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Conflict) GetBaseHash() string {
	if x != nil {
		return x.BaseHash
	}
	return ""
}

func (x *Conflict) GetServerHash() string {
	if x != nil {
		return x.ServerHash
	}
	return ""
}

func (x *Conflict) GetServerMtime() int64 {
	if x != nil {
		return x.ServerMtime
	}
	return 0
}

func (x *Conflict) GetLocalHash() string {
	if x != nil {
		return x.LocalHash
	}
	return ""
}

func (x *Conflict) GetIsNote() bool {
	if x != nil {
		return x.IsNote
	}
	return false
}

// Change 提交素材的一条变更
type Change struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            string                 `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`                          // add | modify | delete | move
	OldPath       string                 `protobuf:"bytes,2,opt,name=old_path,json=oldPath,proto3" json:"old_path,omitempty"` // move 专用
	Item          *ManifestItem          `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Change) Reset() {
	*x = Change{}
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Change) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Change) ProtoMessage() {}

func (x *Change) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Change.ProtoReflect.Descriptor instead.
func (*Change) Descriptor() ([]byte, []int) {
	return file_internal_proto_v3_sync_v3_proto_rawDescGZIP(), []int{8}
}

func (x *Change) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *Change) GetOldPath() string {
	if x != nil {
		return x.OldPath
	}
	return ""
}

func (x *Change) GetItem() *ManifestItem {
	if x != nil {
		return x.Item
	}
	return nil
}

// V3Sync（C→S）
type V3SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vault         string                 `protobuf:"bytes,1,opt,name=vault,proto3" json:"vault,omitempty"`
	BaseEpoch     int64                  `protobuf:"varint,2,opt,name=base_epoch,json=baseEpoch,proto3" json:"base_epoch,omitempty"`
	Manifest      []*ManifestItem        `protobuf:"bytes,3,rep,name=manifest,proto3" json:"manifest,omitempty"`
	Tombstones    []*Tombstone           `protobuf:"bytes,4,rep,name=tombstones,proto3" json:"tombstones,omitempty"`
	Scope         *Scope                 `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V3SyncRequest) Reset() {
	*x = V3SyncRequest{}
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V3SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V3SyncRequest) ProtoMessage() {}

func (x *V3SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V3SyncRequest.ProtoReflect.Descriptor instead.
func (*V3SyncRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_v3_sync_v3_proto_rawDescGZIP(), []int{9}
}

func (x *V3SyncRequest) GetVault() string {
	if x != nil {
		return x.Vault
	}
	return ""
}

func (x *V3SyncRequest) GetBaseEpoch() int64 {
	if x != nil {
		return x.BaseEpoch
	}
	return 0
}

func (x *V3SyncRequest) GetManifest() []*ManifestItem {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *V3SyncRequest) GetTombstones() []*Tombstone {
	if x != nil {
		return x.Tombstones
	}
	return nil
}

func (x *V3SyncRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

// V3SyncPlan（S→C）
type V3SyncPlanMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vault         string                 `protobuf:"bytes,1,opt,name=vault,proto3" json:"vault,omitempty"`
	ServerEpoch   int64                  `protobuf:"varint,2,opt,name=server_epoch,json=serverEpoch,proto3" json:"server_epoch,omitempty"`
	BaseEpoch     int64                  `protobuf:"varint,3,opt,name=base_epoch,json=baseEpoch,proto3" json:"base_epoch,omitempty"`
	Ops           []*Op                  `protobuf:"bytes,4,rep,name=ops,proto3" json:"ops,omitempty"`
	Conflicts     []*Conflict            `protobuf:"bytes,5,rep,name=conflicts,proto3" json:"conflicts,omitempty"`
	Expected      []*Change              `protobuf:"bytes,6,rep,name=expected,proto3" json:"expected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V3SyncPlanMessage) Reset() {
	*x = V3SyncPlanMessage{}
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V3SyncPlanMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V3SyncPlanMessage) ProtoMessage() {}

func (x *V3SyncPlanMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V3SyncPlanMessage.ProtoReflect.Descriptor instead.
func (*V3SyncPlanMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_v3_sync_v3_proto_rawDescGZIP(), []int{10}
}

func (x *V3SyncPlanMessage) GetVault() string {
	if x != nil {
		return x.Vault
	}
	return ""
}

func (x *V3SyncPlanMessage) GetServerEpoch() int64 {
	if x != nil {
		return x.ServerEpoch
	}
	return 0
}

func (x *V3SyncPlanMessage) GetBaseEpoch() int64 {
	if x != nil {
		return x.BaseEpoch
	}
	return 0
}

func (x *V3SyncPlanMessage) GetOps() []*Op {
	if x != nil {
		return x.Ops
	}
	return nil
}

func (x *V3SyncPlanMessage) GetConflicts() []*Conflict {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

func (x *V3SyncPlanMessage) GetExpected() []*Change {
	if x != nil {
		return x.Expected
	}
	return nil
}

// V3BlobNeed（S→C）
type V3BlobNeedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vault         string                 `protobuf:"bytes,1,opt,name=vault,proto3" json:"vault,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V3BlobNeedMessage) Reset() {
	*x = V3BlobNeedMessage{}
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V3BlobNeedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V3BlobNeedMessage) ProtoMessage() {}

func (x *V3BlobNeedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V3BlobNeedMessage.ProtoReflect.Descriptor instead.
func (*V3BlobNeedMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_v3_sync_v3_proto_rawDescGZIP(), []int{11}
}

func (x *V3BlobNeedMessage) GetVault() string {
	if x != nil {
		return x.Vault
	}
	return ""
}

func (x *V3BlobNeedMessage) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *V3BlobNeedMessage) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *V3BlobNeedMessage) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// V3BlobPage（S→C，笔记文本内联）
type V3BlobPageMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vault         string                 `protobuf:"bytes,1,opt,name=vault,proto3" json:"vault,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	IsNote        bool                   `protobuf:"varint,5,opt,name=is_note,json=isNote,proto3" json:"is_note,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V3BlobPageMessage) Reset() {
	*x = V3BlobPageMessage{}
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V3BlobPageMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V3BlobPageMessage) ProtoMessage() {}

func (x *V3BlobPageMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V3BlobPageMessage.ProtoReflect.Descriptor instead.
func (*V3BlobPageMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_v3_sync_v3_proto_rawDescGZIP(), []int{12}
}

func (x *V3BlobPageMessage) GetVault() string {
	if x != nil {
		return x.Vault
	}
	return ""
}

func (x *V3BlobPageMessage) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *V3BlobPageMessage) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *V3BlobPageMessage) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *V3BlobPageMessage) GetIsNote() bool {
	if x != nil {
		return x.IsNote
	}
	return false
}

func (x *V3BlobPageMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// V3Commit（C→S）
type V3ManifestCommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vault         string                 `protobuf:"bytes,1,opt,name=vault,proto3" json:"vault,omitempty"`
	BaseEpoch     int64                  `protobuf:"varint,2,opt,name=base_epoch,json=baseEpoch,proto3" json:"base_epoch,omitempty"`
	Changes       []*Change              `protobuf:"bytes,3,rep,name=changes,proto3" json:"changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V3ManifestCommitRequest) Reset() {
	*x = V3ManifestCommitRequest{}
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V3ManifestCommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V3ManifestCommitRequest) ProtoMessage() {}

func (x *V3ManifestCommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V3ManifestCommitRequest.ProtoReflect.Descriptor instead.
func (*V3ManifestCommitRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_v3_sync_v3_proto_rawDescGZIP(), []int{13}
}

func (x *V3ManifestCommitRequest) GetVault() string {
	if x != nil {
		return x.Vault
	}
	return ""
}

func (x *V3ManifestCommitRequest) GetBaseEpoch() int64 {
	if x != nil {
		return x.BaseEpoch
	}
	return 0
}

func (x *V3ManifestCommitRequest) GetChanges() []*Change {
	if x != nil {
		return x.Changes
	}
	return nil
}

// V3CommitAck（S→C）
type V3CommitAckItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V3CommitAckItem) Reset() {
	*x = V3CommitAckItem{}
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V3CommitAckItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V3CommitAckItem) ProtoMessage() {}

func (x *V3CommitAckItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V3CommitAckItem.ProtoReflect.Descriptor instead.
func (*V3CommitAckItem) Descriptor() ([]byte, []int) {
	return file_internal_proto_v3_sync_v3_proto_rawDescGZIP(), []int{14}
}

func (x *V3CommitAckItem) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *V3CommitAckItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type V3ManifestCommitAckMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vault         string                 `protobuf:"bytes,1,opt,name=vault,proto3" json:"vault,omitempty"`
	NewEpoch      int64                  `protobuf:"varint,2,opt,name=new_epoch,json=newEpoch,proto3" json:"new_epoch,omitempty"`
	Items         []*V3CommitAckItem     `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V3ManifestCommitAckMessage) Reset() {
	*x = V3ManifestCommitAckMessage{}
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V3ManifestCommitAckMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V3ManifestCommitAckMessage) ProtoMessage() {}

func (x *V3ManifestCommitAckMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V3ManifestCommitAckMessage.ProtoReflect.Descriptor instead.
func (*V3ManifestCommitAckMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_v3_sync_v3_proto_rawDescGZIP(), []int{15}
}

func (x *V3ManifestCommitAckMessage) GetVault() string {
	if x != nil {
		return x.Vault
	}
	return ""
}

func (x *V3ManifestCommitAckMessage) GetNewEpoch() int64 {
	if x != nil {
		return x.NewEpoch
	}
	return 0
}

func (x *V3ManifestCommitAckMessage) GetItems() []*V3CommitAckItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// V3NotifyManifest（S→C 广播）
type V3NotifyManifestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vault         string                 `protobuf:"bytes,1,opt,name=vault,proto3" json:"vault,omitempty"`
	NewEpoch      int64                  `protobuf:"varint,2,opt,name=new_epoch,json=newEpoch,proto3" json:"new_epoch,omitempty"`
	Ops           []*Op                  `protobuf:"bytes,3,rep,name=ops,proto3" json:"ops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V3NotifyManifestMessage) Reset() {
	*x = V3NotifyManifestMessage{}
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V3NotifyManifestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V3NotifyManifestMessage) ProtoMessage() {}

func (x *V3NotifyManifestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V3NotifyManifestMessage.ProtoReflect.Descriptor instead.
func (*V3NotifyManifestMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_v3_sync_v3_proto_rawDescGZIP(), []int{16}
}

func (x *V3NotifyManifestMessage) GetVault() string {
	if x != nil {
		return x.Vault
	}
	return ""
}

func (x *V3NotifyManifestMessage) GetNewEpoch() int64 {
	if x != nil {
		return x.NewEpoch
	}
	return 0
}

func (x *V3NotifyManifestMessage) GetOps() []*Op {
	if x != nil {
		return x.Ops
	}
	return nil
}

// V3BlobUpload（C→S）
type V3BlobUploadOpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vault         string                 `protobuf:"bytes,1,opt,name=vault,proto3" json:"vault,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V3BlobUploadOpenRequest) Reset() {
	*x = V3BlobUploadOpenRequest{}
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V3BlobUploadOpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V3BlobUploadOpenRequest) ProtoMessage() {}

func (x *V3BlobUploadOpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V3BlobUploadOpenRequest.ProtoReflect.Descriptor instead.
func (*V3BlobUploadOpenRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_v3_sync_v3_proto_rawDescGZIP(), []int{17}
}

func (x *V3BlobUploadOpenRequest) GetVault() string {
	if x != nil {
		return x.Vault
	}
	return ""
}

func (x *V3BlobUploadOpenRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *V3BlobUploadOpenRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// V3BlobUploadOpenAck（S→C；exists=true 即秒传）
type V3BlobUploadOpenMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vault         string                 `protobuf:"bytes,1,opt,name=vault,proto3" json:"vault,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ChunkSize     int64                  `protobuf:"varint,4,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	TotalChunks   int64                  `protobuf:"varint,5,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	Exists        bool                   `protobuf:"varint,6,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V3BlobUploadOpenMessage) Reset() {
	*x = V3BlobUploadOpenMessage{}
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V3BlobUploadOpenMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V3BlobUploadOpenMessage) ProtoMessage() {}

func (x *V3BlobUploadOpenMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V3BlobUploadOpenMessage.ProtoReflect.Descriptor instead.
func (*V3BlobUploadOpenMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_v3_sync_v3_proto_rawDescGZIP(), []int{18}
}

func (x *V3BlobUploadOpenMessage) GetVault() string {
	if x != nil {
		return x.Vault
	}
	return ""
}

func (x *V3BlobUploadOpenMessage) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *V3BlobUploadOpenMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *V3BlobUploadOpenMessage) GetChunkSize() int64 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *V3BlobUploadOpenMessage) GetTotalChunks() int64 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *V3BlobUploadOpenMessage) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

// V3BlobUploadAck（S→C，分块全部到齐）
type V3BlobUploadAckMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vault         string                 `protobuf:"bytes,1,opt,name=vault,proto3" json:"vault,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V3BlobUploadAckMessage) Reset() {
	*x = V3BlobUploadAckMessage{}
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V3BlobUploadAckMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V3BlobUploadAckMessage) ProtoMessage() {}

func (x *V3BlobUploadAckMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V3BlobUploadAckMessage.ProtoReflect.Descriptor instead.
func (*V3BlobUploadAckMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_v3_sync_v3_proto_rawDescGZIP(), []int{19}
}

func (x *V3BlobUploadAckMessage) GetVault() string {
	if x != nil {
		return x.Vault
	}
	return ""
}

func (x *V3BlobUploadAckMessage) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *V3BlobUploadAckMessage) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// V3BlobDownload（C→S）
type V3BlobDownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vault         string                 `protobuf:"bytes,1,opt,name=vault,proto3" json:"vault,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	ChunkIndex    uint32                 `protobuf:"varint,3,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V3BlobDownloadRequest) Reset() {
	*x = V3BlobDownloadRequest{}
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V3BlobDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V3BlobDownloadRequest) ProtoMessage() {}

func (x *V3BlobDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V3BlobDownloadRequest.ProtoReflect.Descriptor instead.
func (*V3BlobDownloadRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_v3_sync_v3_proto_rawDescGZIP(), []int{20}
}

func (x *V3BlobDownloadRequest) GetVault() string {
	if x != nil {
		return x.Vault
	}
	return ""
}

func (x *V3BlobDownloadRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *V3BlobDownloadRequest) GetChunkIndex() uint32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

// V3BlobChunk（S→C，单分块）
type V3BlobChunkMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vault         string                 `protobuf:"bytes,1,opt,name=vault,proto3" json:"vault,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	ChunkIndex    uint32                 `protobuf:"varint,3,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	TotalChunks   int64                  `protobuf:"varint,4,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	ChunkSize     int64                  `protobuf:"varint,5,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	Size          int64                  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	Data          string                 `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"` // base64（与 JSON 帧一致；二进制分块通道是 "01" 上行专用）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V3BlobChunkMessage) Reset() {
	*x = V3BlobChunkMessage{}
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V3BlobChunkMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V3BlobChunkMessage) ProtoMessage() {}

func (x *V3BlobChunkMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v3_sync_v3_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V3BlobChunkMessage.ProtoReflect.Descriptor instead.
func (*V3BlobChunkMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_v3_sync_v3_proto_rawDescGZIP(), []int{21}
}

func (x *V3BlobChunkMessage) GetVault() string {
	if x != nil {
		return x.Vault
	}
	return ""
}

func (x *V3BlobChunkMessage) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *V3BlobChunkMessage) GetChunkIndex() uint32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *V3BlobChunkMessage) GetTotalChunks() int64 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *V3BlobChunkMessage) GetChunkSize() int64 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *V3BlobChunkMessage) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *V3BlobChunkMessage) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_internal_proto_v3_sync_v3_proto protoreflect.FileDescriptor

const file_internal_proto_v3_sync_v3_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/proto/v3/sync_v3.proto\x12\x06fns.v3\"3\n" +
	"\tWSMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\xce\x01\n" +
	"\n" +
	"WSResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x16\n" +
	"\x06status\x18\x02 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x18\n" +
	"\adetails\x18\x05 \x01(\tR\adetails\x12\x14\n" +
	"\x05vault\x18\x06 \x01(\tR\x05vault\x12\x18\n" +
	"\acontext\x18\a \x01(\tR\acontext\x12\x1c\n" +
	"\tpageIndex\x18\b \x01(\x05R\tpageIndex\"\xe7\x02\n" +
	"\x11ClientInfoMessage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"is_desktop\x18\x04 \x01(\bR\tisDesktop\x12\x1b\n" +
	"\tis_mobile\x18\x05 \x01(\bR\bisMobile\x12\x19\n" +
	"\bis_phone\x18\x06 \x01(\bR\aisPhone\x12\x1b\n" +
	"\tis_tablet\x18\a \x01(\bR\bisTablet\x12\x1a\n" +
	"\tis_mac_os\x18\b \x01(\bR\aisMacOs\x12\x15\n" +
	"\x06is_win\x18\t \x01(\bR\x05isWin\x12\x19\n" +
	"\bis_linux\x18\n" +
	" \x01(\bR\aisLinux\x122\n" +
	"\x15offline_sync_strategy\x18\v \x01(\tR\x13offlineSyncStrategy\x12\x1a\n" +
	"\bprotobuf\x18\f \x01(\bR\bprotobuf\"\x9f\x01\n" +
	"\fManifestItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12\x17\n" +
	"\ais_note\x18\x04 \x01(\bR\x06isNote\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\x12\x14\n" +
	"\x05mtime\x18\x06 \x01(\x03R\x05mtime\x12\x14\n" +
	"\x05ctime\x18\a \x01(\x03R\x05ctime\"/\n" +
	"\tTombstone\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"Q\n" +
	"\x05Scope\x12\x18\n" +
	"\ainclude\x18\x01 \x03(\tR\ainclude\x12\x18\n" +
	"\aexclude\x18\x02 \x03(\tR\aexclude\x12\x14\n" +
	"\x05types\x18\x03 \x03(\tR\x05types\"R\n" +
	"\x02Op\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\tR\x02op\x12(\n" +
	"\x04item\x18\x02 \x01(\v2\x14.fns.v3.ManifestItemR\x04item\x12\x12\n" +
	"\x04from\x18\x03 \x01(\tR\x04from\"\xdb\x01\n" +
	"\bConflict\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x1b\n" +
	"\tbase_hash\x18\x04 \x01(\tR\bbaseHash\x12\x1f\n" +
	"\vserver_hash\x18\x05 \x01(\tR\n" +
	"serverHash\x12!\n" +
	"\fserver_mtime\x18\x06 \x01(\x03R\vserverMtime\x12\x1d\n" +
	"\n" +
	"local_hash\x18\a \x01(\tR\tlocalHash\x12\x17\n" +
	"\ais_note\x18\b \x01(\bR\x06isNote\"]\n" +
	"\x06Change\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\tR\x02op\x12\x19\n" +
	"\bold_path\x18\x02 \x01(\tR\aoldPath\x12(\n" +
	"\x04item\x18\x03 \x01(\v2\x14.fns.v3.ManifestItemR\x04item\"\xce\x01\n" +
	"\rV3SyncRequest\x12\x14\n" +
	"\x05vault\x18\x01 \x01(\tR\x05vault\x12\x1d\n" +
	"\n" +
	"base_epoch\x18\x02 \x01(\x03R\tbaseEpoch\x120\n" +
	"\bmanifest\x18\x03 \x03(\v2\x14.fns.v3.ManifestItemR\bmanifest\x121\n" +
	"\n" +
	"tombstones\x18\x04 \x03(\v2\x11.fns.v3.TombstoneR\n" +
	"tombstones\x12#\n" +
	"\x05scope\x18\x05 \x01(\v2\r.fns.v3.ScopeR\x05scope\"\xe5\x01\n" +
	"\x11V3SyncPlanMessage\x12\x14\n" +
	"\x05vault\x18\x01 \x01(\tR\x05vault\x12!\n" +
	"\fserver_epoch\x18\x02 \x01(\x03R\vserverEpoch\x12\x1d\n" +
	"\n" +
	"base_epoch\x18\x03 \x01(\x03R\tbaseEpoch\x12\x1c\n" +
	"\x03ops\x18\x04 \x03(\v2\n" +
	".fns.v3.OpR\x03ops\x12.\n" +
	"\tconflicts\x18\x05 \x03(\v2\x10.fns.v3.ConflictR\tconflicts\x12*\n" +
	"\bexpected\x18\x06 \x03(\v2\x0e.fns.v3.ChangeR\bexpected\"e\n" +
	"\x11V3BlobNeedMessage\x12\x14\n" +
	"\x05vault\x18\x01 \x01(\tR\x05vault\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\"\x98\x01\n" +
	"\x11V3BlobPageMessage\x12\x14\n" +
	"\x05vault\x18\x01 \x01(\tR\x05vault\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x17\n" +
	"\ais_note\x18\x05 \x01(\bR\x06isNote\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\"x\n" +
	"\x17V3ManifestCommitRequest\x12\x14\n" +
	"\x05vault\x18\x01 \x01(\tR\x05vault\x12\x1d\n" +
	"\n" +
	"base_epoch\x18\x02 \x01(\x03R\tbaseEpoch\x12(\n" +
	"\achanges\x18\x03 \x03(\v2\x0e.fns.v3.ChangeR\achanges\"5\n" +
	"\x0fV3CommitAckItem\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"~\n" +
	"\x1aV3ManifestCommitAckMessage\x12\x14\n" +
	"\x05vault\x18\x01 \x01(\tR\x05vault\x12\x1b\n" +
	"\tnew_epoch\x18\x02 \x01(\x03R\bnewEpoch\x12-\n" +
	"\x05items\x18\x03 \x03(\v2\x17.fns.v3.V3CommitAckItemR\x05items\"j\n" +
	"\x17V3NotifyManifestMessage\x12\x14\n" +
	"\x05vault\x18\x01 \x01(\tR\x05vault\x12\x1b\n" +
	"\tnew_epoch\x18\x02 \x01(\x03R\bnewEpoch\x12\x1c\n" +
	"\x03ops\x18\x03 \x03(\v2\n" +
	".fns.v3.OpR\x03ops\"W\n" +
	"\x17V3BlobUploadOpenRequest\x12\x14\n" +
	"\x05vault\x18\x01 \x01(\tR\x05vault\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"\xbc\x01\n" +
	"\x17V3BlobUploadOpenMessage\x12\x14\n" +
	"\x05vault\x18\x01 \x01(\tR\x05vault\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x04 \x01(\x03R\tchunkSize\x12!\n" +
	"\ftotal_chunks\x18\x05 \x01(\x03R\vtotalChunks\x12\x16\n" +
	"\x06exists\x18\x06 \x01(\bR\x06exists\"V\n" +
	"\x16V3BlobUploadAckMessage\x12\x14\n" +
	"\x05vault\x18\x01 \x01(\tR\x05vault\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"b\n" +
	"\x15V3BlobDownloadRequest\x12\x14\n" +
	"\x05vault\x18\x01 \x01(\tR\x05vault\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x1f\n" +
	"\vchunk_index\x18\x03 \x01(\rR\n" +
	"chunkIndex\"\xc9\x01\n" +
	"\x12V3BlobChunkMessage\x12\x14\n" +
	"\x05vault\x18\x01 \x01(\tR\x05vault\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x1f\n" +
	"\vchunk_index\x18\x03 \x01(\rR\n" +
	"chunkIndex\x12!\n" +
	"\ftotal_chunks\x18\x04 \x01(\x03R\vtotalChunks\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x05 \x01(\x03R\tchunkSize\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\x12\x12\n" +
	"\x04data\x18\a \x01(\tR\x04dataB?Z=github.com/haierkeys/fast-note-sync-service/internal/proto/v3b\x06proto3"

var (
	file_internal_proto_v3_sync_v3_proto_rawDescOnce sync.Once
	file_internal_proto_v3_sync_v3_proto_rawDescData []byte
)

func file_internal_proto_v3_sync_v3_proto_rawDescGZIP() []byte {
	file_internal_proto_v3_sync_v3_proto_rawDescOnce.Do(func() {
		file_internal_proto_v3_sync_v3_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_v3_sync_v3_proto_rawDesc), len(file_internal_proto_v3_sync_v3_proto_rawDesc)))
	})
	return file_internal_proto_v3_sync_v3_proto_rawDescData
}

var file_internal_proto_v3_sync_v3_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_internal_proto_v3_sync_v3_proto_goTypes = []any{
	(*WSMessage)(nil),                  // 0: fns.v3.WSMessage
	(*WSResponse)(nil),                 // 1: fns.v3.WSResponse
	(*ClientInfoMessage)(nil),          // 2: fns.v3.ClientInfoMessage
	(*ManifestItem)(nil),               // 3: fns.v3.ManifestItem
	(*Tombstone)(nil),                  // 4: fns.v3.Tombstone
	(*Scope)(nil),                      // 5: fns.v3.Scope
	(*Op)(nil),                         // 6: fns.v3.Op
	(*Conflict)(nil),                   // 7: fns.v3.Conflict
	(*Change)(nil),                     // 8: fns.v3.Change
	(*V3SyncRequest)(nil),              // 9: fns.v3.V3SyncRequest
	(*V3SyncPlanMessage)(nil),          // 10: fns.v3.V3SyncPlanMessage
	(*V3BlobNeedMessage)(nil),          // 11: fns.v3.V3BlobNeedMessage
	(*V3BlobPageMessage)(nil),          // 12: fns.v3.V3BlobPageMessage
	(*V3ManifestCommitRequest)(nil),    // 13: fns.v3.V3ManifestCommitRequest
	(*V3CommitAckItem)(nil),            // 14: fns.v3.V3CommitAckItem
	(*V3ManifestCommitAckMessage)(nil), // 15: fns.v3.V3ManifestCommitAckMessage
	(*V3NotifyManifestMessage)(nil),    // 16: fns.v3.V3NotifyManifestMessage
	(*V3BlobUploadOpenRequest)(nil),    // 17: fns.v3.V3BlobUploadOpenRequest
	(*V3BlobUploadOpenMessage)(nil),    // 18: fns.v3.V3BlobUploadOpenMessage
	(*V3BlobUploadAckMessage)(nil),     // 19: fns.v3.V3BlobUploadAckMessage
	(*V3BlobDownloadRequest)(nil),      // 20: fns.v3.V3BlobDownloadRequest
	(*V3BlobChunkMessage)(nil),         // 21: fns.v3.V3BlobChunkMessage
}
var file_internal_proto_v3_sync_v3_proto_depIdxs = []int32{
	3,  // 0: fns.v3.Op.item:type_name -> fns.v3.ManifestItem
	3,  // 1: fns.v3.Change.item:type_name -> fns.v3.ManifestItem
	3,  // 2: fns.v3.V3SyncRequest.manifest:type_name -> fns.v3.ManifestItem
	4,  // 3: fns.v3.V3SyncRequest.tombstones:type_name -> fns.v3.Tombstone
	5,  // 4: fns.v3.V3SyncRequest.scope:type_name -> fns.v3.Scope
	6,  // 5: fns.v3.V3SyncPlanMessage.ops:type_name -> fns.v3.Op
	7,  // 6: fns.v3.V3SyncPlanMessage.conflicts:type_name -> fns.v3.Conflict
	8,  // 7: fns.v3.V3SyncPlanMessage.expected:type_name -> fns.v3.Change
	8,  // 8: fns.v3.V3ManifestCommitRequest.changes:type_name -> fns.v3.Change
	14, // 9: fns.v3.V3ManifestCommitAckMessage.items:type_name -> fns.v3.V3CommitAckItem
	6,  // 10: fns.v3.V3NotifyManifestMessage.ops:type_name -> fns.v3.Op
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_internal_proto_v3_sync_v3_proto_init() }
func file_internal_proto_v3_sync_v3_proto_init() {
	if File_internal_proto_v3_sync_v3_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_v3_sync_v3_proto_rawDesc), len(file_internal_proto_v3_sync_v3_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_v3_sync_v3_proto_goTypes,
		DependencyIndexes: file_internal_proto_v3_sync_v3_proto_depIdxs,
		MessageInfos:      file_internal_proto_v3_sync_v3_proto_msgTypes,
	}.Build()
	File_internal_proto_v3_sync_v3_proto = out.File
	file_internal_proto_v3_sync_v3_proto_goTypes = nil
	file_internal_proto_v3_sync_v3_proto_depIdxs = nil
}
